name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Security and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up Trivy
        run: |
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.30.0/trivy_0.30.0_Linux-64bit.tar.gz | tar xz -C /usr/local/bin 
      
      # Run Trivy Security Scan
      - name: Run Trivy Security Scan
        run: |
         trivy fs --format json --output trivy_scan_results.json .
          
          
      - name: Upload Trivy Results
        uses: actions/upload-artifact@v2
        with:
           name: trivy-scan-results
           path: trivy_scan_results.json
           
      # Stop Deployment if High or Critical vulnerabilities are found
      - name: Fail on High-Severity Issues
        run: |
          if grep -q "CRITICAL\|HIGH" trivy-report.txt; then
            echo "Critical or High vulnerabilities found! Failing the job."
            exit 1
          fi

      # Run Python Unit Tests
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r src/requirements.txt

      - name: Run Unit Tests
        run: |
          export PYTHONPATH=src:$PYTHONPATH  # Add src to the Python path
          pytest tests/
        
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create Zip file for Lambda function
        run: |
          cd src
          zip -r ../code.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:211125625532:function:TestFunction \
            --zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
